# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  retrofit:
    target: ":retrofit"
    import: "package:retrofit_generator/retrofit_generator.dart"
    builder_factories: ["retrofitBuilder"]
    build_extensions: { ".dart": [".retrofit.dart"] }
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
