name: retrofit_generator
description: Retrofit generator
version: 0.0.1
author: Trevor Wang <trevor.wang@qq.com>
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  dio:
  source_gen:
  built_collection:
  code_builder:
  tuple:
  retrofit:

dependency_overrides:
  retrofit:
    path: ../annotation
