kind: pipeline
name: default

steps:
  - name: test
    image: google/dart
    commands:
      - cd /drone/src/example && pub get && pub run build_runner build  && pub run test
      - cd /drone/src && PKGS="example annotation generator" ./tool/travis.sh dartanalyzer
      - cd /drone/src/generator && pub get && pub run test
