name: retrofit
version: 0.6.0

authors:
  - Trevor Wang <trevor.wang@qq.com>
  - Dinesh Ahuja <dev@kabiir.me>

homepage: https://mings.in/retrofit.dart/
description: retrofit.dart is an dio client generator using source_gen and inspired by Chopper and Retrofit.

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  meta: ^1.1.6
