name: Star Checker

on:
  issues:
    types: [opened, reopened]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: trevorwang/no-free-usage-action@v1.0.1
    - name: Check user stars
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
